export default [
    {
        title: 'lorem ipsum blog post',
        price: 12,
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio.',
        datePublished: '2024-02-12',
        isFeatured: true,
        wordCount: 1200,
        readingTime: 5.5,
        url: 'https://example.com/lorem-ipsum',
        media: 'https://gravatar.com/avatar/1?s=400&d=robohash',
    },
    {
        title: 'pellentesque nec blog post',
        price: 10.75,
        content:
            'Pellentesque nec nisl vitae massa egestas tristique. Mauris auctor consequat justo.',
        datePublished: '2024-02-13',
        isFeatured: false,
        wordCount: 800,
        readingTime: 3.8,
        url: 'https://example.com/pellentesque-nec',
        media: 'https://gravatar.com/unkown-url',
    },
    {
        title: 'fusce sit amet blog post',
        price: 1100,
        content:
            'Fusce sit amet justo vitae libero finibus viverra. Sed tincidunt risus eu tortor fermentum blandit.',
        datePublished: '2024-02-14',
        isFeatured: true,
        wordCount: 1500,
        readingTime: 7.2,
        url: 'https://example.com/fusce-sit-amet',
        media: 'https://loremflickr.com/cache/resized/65535_52821605306_fb553abe7e_k_673_1280_nofilter.jpg',
    },
    {
        title: 'vestibulum nec blog post',
        price: 0,
        content: 'Vestibulum nec ante non dui cursus fermentum. Suspendisse eu aliquam turpis.',
        datePublished: '2024-02-15',
        isFeatured: false,
        wordCount: 1000,
        readingTime: 4.5,
        url: 'https://example.com/vestibulum-nec',
        media: 'https://gravatar.com/avatar/4?s=400&d=robohash',
    },
    {
        title: 'Cras At Blog Post',
        price: 1,
        content:
            'Cras at odio eget nisi bibendum aliquam id nec nisl. Donec ultricies nisi vel arcu rhoncus, nec pellentesque mauris aliquam.',
        datePublished: '2024-02-16',
        isFeatured: true,
        wordCount: 1300,
        readingTime: 6.0,
        url: 'https://example.com/cras-at',
        media: 'https://gravatar.com/avatar/5?s=400&d=robohash',
    },
    {
        title: 'Quisque A Blog Post',
        price: 0.99,
        content:
            'Quisque a sem sit amet turpis scelerisque volutpat a et arcu. Aenean luctus venenatis ex, non accumsan odio accumsan et.',
        datePublished: '2024-02-17',
        isFeatured: false,
        wordCount: 900,
        readingTime: 4.0,
        url: 'https://example.com/quisque-a',
        media: 'https://gravatar.com/avatar/6?s=400&d=robohash',
    },
    {
        title: 'Ut Vitae Blog Post',
        price: 10,
        content:
            'Ut vitae eros sit amet felis tincidunt tristique. Nullam non nisi nec justo rhoncus imperdiet.',
        datePublished: '2024-02-18',
        isFeatured: true,
        wordCount: 1100,
        readingTime: 5.0,
        url: 'https://example.com/ut-vitae',
        media: 'https://gravatar.com/avatar/7?s=400&d=robohash',
    },
    {
        title: 'Integer Id Blog Post',
        price: 5,
        content:
            'Integer id lectus vitae justo euismod finibus. Aliquam a sem at lectus gravida luctus.',
        datePublished: '2024-02-19',
        isFeatured: false,
        wordCount: 950,
        readingTime: 4.2,
        url: 'https://example.com/integer-id',
        media: 'https://gravatar.com/avatar/8?s=400&d=robohash',
    },
    {
        title: 'Undefined row',
        price: undefined,
        content: null,
        datePublished: undefined,
        isFeatured: null,
        wordCount: undefined,
        readingTime: null,
        url: undefined,
        media: undefined,
    },
    {
        title: 'Empty row',
    },
];
