name: api-client coverage
on:
  pull_request:
    paths:
    - 'packages/api-client/**'
  push:
    branches:
      - main
jobs:
  build:
    name: Get api client test coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install
        run: npm ci
        working-directory: ./packages/api-client

      - name: lint
        run: npm run lint:eslint:check && npm run lint:prettier:check
        working-directory: ./packages/api-client
      
      - name: test
        run: npm run test
        working-directory: ./packages/api-client

      - name: Coverage
        run: npm run test:coverage
        working-directory: ./packages/api-client

      - name: Comment
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./packages/api-client/coverage/lcov.info
